In [32]:
import numpy as np
import pandas as pd
import utils
import seaborn as sn
import matplotlib.pyplot as plt

In [33]:
data = pd.read_csv('data/results.csv', index_col=0)
data.head()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,_OPN9,_OPN10,EXT,EST,AGR,CSN,OPN,MAX_SCORE,WINNER,CONFLICT
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,4.0,5.0,46.0,36.0,39.0,32.0,45.0,46.0,EXT,False
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,5.0,3.0,20.0,35.0,40.0,37.0,35.0,40.0,AGR,False
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,4.0,4.0,25.0,34.0,40.0,34.0,41.0,41.0,OPN,False
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,3.0,3.0,26.0,31.0,38.0,25.0,39.0,39.0,OPN,False
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,...,5.0,5.0,29.0,41.0,42.0,48.0,48.0,48.0,CSN,True

In [34]:
data=data.drop(['WINNER','CONFLICT'], axis=1)
data.head()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,_OPN7,_OPN8,_OPN9,_OPN10,EXT,EST,AGR,CSN,OPN,MAX_SCORE
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,5.0,3.0,4.0,5.0,46.0,36.0,39.0,32.0,45.0,46.0
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,4.0,2.0,5.0,3.0,20.0,35.0,40.0,37.0,35.0,40.0
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,5.0,3.0,4.0,4.0,25.0,34.0,40.0,34.0,41.0,41.0
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,4.0,4.0,3.0,3.0,26.0,31.0,38.0,25.0,39.0,39.0
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,...,5.0,3.0,5.0,5.0,29.0,41.0,42.0,48.0,48.0,48.0

In [121]:
data['TYPE']=None
data['CORR']=None
data.head()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,_OPN9,_OPN10,EXT,EST,AGR,CSN,OPN,MAX_SCORE,TYPE,CORR
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,4.0,5.0,46.0,36.0,39.0,32.0,45.0,46.0,None,None
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,5.0,3.0,20.0,35.0,40.0,37.0,35.0,40.0,None,None
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,4.0,4.0,25.0,34.0,40.0,34.0,41.0,41.0,None,None
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,3.0,3.0,26.0,31.0,38.0,25.0,39.0,39.0,None,None
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,...,5.0,5.0,29.0,41.0,42.0,48.0,48.0,48.0,None,None

In [122]:
data['TYPE']=None
data['CORR']=None
i=0
min_corr=0.70
for index1, row1 in data.iterrows():
    count=0
    if data.iloc[index1]['TYPE']==None:
#         print('index1:', i, index1)
        print(i)
        data.at[index1,'TYPE']=i
        for index2, row2 in data.iterrows():
#             print(np.corrcoef(row1.iloc[:50].tolist(), row2.iloc[:50].tolist())[0][1])
#             print('index2:', index2, np.corrcoef(data.iloc[index1,100:105].tolist(), data.iloc[index2,100:105].tolist())[0][1])
            corr = np.corrcoef(row1.iloc[100:105].tolist(), row2.iloc[100:105].tolist())[0][1]
            if (corr >= min_corr and data.iloc[index2]['CORR']==None) or (corr >= min_corr and data.iloc[index2]['CORR'] < corr) :
                data.at[index2,'TYPE']=i
                data.at[index2,'CORR']=corr
                count+=1
        i=i+1
        print('count:', count)
    else:
        pass
    
data.head()

0

C:\Users\Karolina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\function_base.py:2854: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\Karolina\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\function_base.py:2855: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

count: 125070
1
count: 215779
2
count: 184153
3
count: 149257
4
count: 22651
5
count: 194964
6
count: 25910
7
count: 33087
8
count: 33532
9
count: 76077
10
count: 197895
11
count: 12838
12
count: 27959
13
count: 27459
14
count: 13778
15
count: 24603
16
count: 31235
17
count: 17696
18
count: 18089
19
count: 46486
20
count: 12751
21
count: 8324
22
count: 19365
23
count: 0
24
count: 19585
25
count: 26867
26
count: 4482
27
count: 46864
28
count: 20449
29
count: 0
30
count: 0
31
count: 0
32
count: 0
33
count: 0
34
count: 0
35
count: 72029
36
count: 0
37
count: 0
38
count: 0
39
count: 0
40
count: 0
41
count: 0
42
count: 0
43
count: 0
44
count: 27008
45
count: 0
46
count: 0
47
count: 0
48
count: 0
49
count: 0
50
count: 0
51
count: 0
52
count: 0
53
count: 0
54
count: 0
55
count: 0
56
count: 0
57
count: 0
58
count: 0
59
count: 0
60
count: 0
61
count: 0
62
count: 0
63
count: 0
64
count: 0
65
count: 0
66
count: 0
67
count: 0
68
count: 0
69
count: 0
70
count: 0
71
count: 0
72
count: 0
73
count: 0
74
count: 0
75
count: 0
76
count: 0
77
count: 0
78
count: 0
79
count: 0
80
count: 0
81
count: 0
82
count: 0
83
count: 0
84
count: 0
85
count: 0
86
count: 0
87
count: 0
88
count: 0
89
count: 0
90
count: 0
91
count: 0
92
count: 0
93
count: 0
94
count: 0
95
count: 0
96
count: 0
97
count: 0
98
count: 0
99
count: 0
100
count: 0
101
count: 0
102
count: 0
103
count: 0
104
count: 0
105
count: 0
106
count: 0
107
count: 0
108
count: 0
109
count: 0
110
count: 0
111
count: 0
112
count: 0
113
count: 0
114
count: 0
115
count: 0
116
count: 0
117
count: 0
118
count: 0
119
count: 0
120
count: 0
121
count: 0
122
count: 0
123
count: 0
124
count: 0
125
count: 0
126
count: 0
127
count: 0
128
count: 0
129
count: 0
130
count: 0
131
count: 0
132
count: 0
133
count: 0
134

KeyboardInterrupt:

In [119]:
data['TYPE'].value_counts()

10    194
5     120
2     116
3      89
1      84
0      79
9      68
19     39
7      29
13     27
16     27
8      22
15     17
12     16
6      14
17     13
18     12
4      10
20      9
14      8
11      7
Name: TYPE, dtype: int64

In [98]:
np.corrcoef(data.iloc[1,100:105].tolist(), data.iloc[2,100:105].tolist())[0][1]

0.8649578919627084

In [110]:
data.head()

,EXT1,EXT2,EXT3,EXT4,EXT5,EXT6,EXT7,EXT8,EXT9,EXT10,...,_OPN9,_OPN10,EXT,EST,AGR,CSN,OPN,MAX_SCORE,TYPE,CORR
0,4.0,1.0,5.0,2.0,5.0,1.0,5.0,2.0,4.0,1.0,...,4.0,5.0,46.0,36.0,39.0,32.0,45.0,46.0,0,1.0
1,3.0,5.0,3.0,4.0,3.0,3.0,2.0,5.0,1.0,5.0,...,5.0,3.0,20.0,35.0,40.0,37.0,35.0,40.0,1,1.0
2,2.0,3.0,4.0,4.0,3.0,2.0,1.0,3.0,2.0,5.0,...,4.0,4.0,25.0,34.0,40.0,34.0,41.0,41.0,1,0.864958
3,2.0,2.0,2.0,3.0,4.0,2.0,2.0,4.0,1.0,4.0,...,3.0,3.0,26.0,31.0,38.0,25.0,39.0,39.0,2,1.0
4,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,3.0,4.0,...,5.0,5.0,29.0,41.0,42.0,48.0,48.0,48.0,7,0.906986

In [106]:
data.iloc[2]['TYPE']

3

In [ ]:
data.to_csv('data/results_corr70.csv')